[package]
name = "memory_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
mimalloc = { version = "0.1", default-features = false }

[dev-dependencies]
criterion = "0.5"
rand = "0.8"

[[bench]]
name = "bench_system"
harness = false

[[bench]]
name = "bench_mimalloc"
harness = false
